// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserRole(ctx context.Context, arg CreateUserRoleParams) (UserRole, error)
	CreateVertifyEmail(ctx context.Context, arg CreateVertifyEmailParams) (VertifyEmail, error)
	DeleteSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetRole(ctx context.Context, roleID pgtype.UUID) (Role, error)
	GetRoleByRoleName(ctx context.Context, roleName string) (Role, error)
	GetRoles(ctx context.Context, arg GetRolesParams) ([]Role, error)
	GetSessionByUserId(ctx context.Context, userID pgtype.UUID) (Session, error)
	GetSessions(ctx context.Context, arg GetSessionsParams) ([]Session, error)
	GetUser(ctx context.Context, userID pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserDTO(ctx context.Context, userID pgtype.UUID) (UserRoleView, error)
	GetUserDTOByEmail(ctx context.Context, email string) (UserRoleView, error)
	GetUserRoleByUserId(ctx context.Context, userID pgtype.UUID) ([]UserRole, error)
	GetUserRoles(ctx context.Context, arg GetUserRolesParams) ([]UserRole, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error)
	GetUsersDTO(ctx context.Context, arg GetUsersDTOParams) ([]UserRoleView, error)
	GetVertifyEmailByUserIdAndCode(ctx context.Context, arg GetVertifyEmailByUserIdAndCodeParams) (VertifyEmail, error)
	GetVertifyEmails(ctx context.Context, arg GetVertifyEmailsParams) ([]VertifyEmail, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UserRole, error)
	UpdateVertifyEmail(ctx context.Context, arg UpdateVertifyEmailParams) (VertifyEmail, error)
}

var _ Querier = (*Queries)(nil)
