// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.0
// source: vertify_email.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendVertifyEmailRequset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *SendVertifyEmailRequset) Reset() {
	*x = SendVertifyEmailRequset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vertify_email_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendVertifyEmailRequset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVertifyEmailRequset) ProtoMessage() {}

func (x *SendVertifyEmailRequset) ProtoReflect() protoreflect.Message {
	mi := &file_vertify_email_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVertifyEmailRequset.ProtoReflect.Descriptor instead.
func (*SendVertifyEmailRequset) Descriptor() ([]byte, []int) {
	return file_vertify_email_proto_rawDescGZIP(), []int{0}
}

func (x *SendVertifyEmailRequset) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type VertifyEmailRequset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SecretCode string `protobuf:"bytes,2,opt,name=secret_code,json=secretCode,proto3" json:"secret_code,omitempty"`
}

func (x *VertifyEmailRequset) Reset() {
	*x = VertifyEmailRequset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vertify_email_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VertifyEmailRequset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VertifyEmailRequset) ProtoMessage() {}

func (x *VertifyEmailRequset) ProtoReflect() protoreflect.Message {
	mi := &file_vertify_email_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VertifyEmailRequset.ProtoReflect.Descriptor instead.
func (*VertifyEmailRequset) Descriptor() ([]byte, []int) {
	return file_vertify_email_proto_rawDescGZIP(), []int{1}
}

func (x *VertifyEmailRequset) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VertifyEmailRequset) GetSecretCode() string {
	if x != nil {
		return x.SecretCode
	}
	return ""
}

type VertifyEmailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *VertifyEmailResponse) Reset() {
	*x = VertifyEmailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vertify_email_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VertifyEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VertifyEmailResponse) ProtoMessage() {}

func (x *VertifyEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vertify_email_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VertifyEmailResponse.ProtoReflect.Descriptor instead.
func (*VertifyEmailResponse) Descriptor() ([]byte, []int) {
	return file_vertify_email_proto_rawDescGZIP(), []int{2}
}

func (x *VertifyEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_vertify_email_proto protoreflect.FileDescriptor

var file_vertify_email_proto_rawDesc = []byte{
	0x0a, 0x13, 0x76, 0x65, 0x72, 0x74, 0x69, 0x66, 0x79, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2f, 0x0a, 0x17, 0x53, 0x65, 0x6e,
	0x64, 0x56, 0x65, 0x72, 0x74, 0x69, 0x66, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x4f, 0x0a, 0x13, 0x56, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x73, 0x65,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x30, 0x0a, 0x14, 0x56,
	0x65, 0x72, 0x74, 0x69, 0x66, 0x79, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x39, 0x5a,
	0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x6f, 0x79, 0x63,
	0x65, 0x41, 0x7a, 0x75, 0x72, 0x65, 0x2f, 0x73, 0x65, 0x78, 0x79, 0x5f, 0x67, 0x70, 0x74, 0x2f,
	0x62, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vertify_email_proto_rawDescOnce sync.Once
	file_vertify_email_proto_rawDescData = file_vertify_email_proto_rawDesc
)

func file_vertify_email_proto_rawDescGZIP() []byte {
	file_vertify_email_proto_rawDescOnce.Do(func() {
		file_vertify_email_proto_rawDescData = protoimpl.X.CompressGZIP(file_vertify_email_proto_rawDescData)
	})
	return file_vertify_email_proto_rawDescData
}

var file_vertify_email_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vertify_email_proto_goTypes = []interface{}{
	(*SendVertifyEmailRequset)(nil), // 0: pb.SendVertifyEmailRequset
	(*VertifyEmailRequset)(nil),     // 1: pb.VertifyEmailRequset
	(*VertifyEmailResponse)(nil),    // 2: pb.VertifyEmailResponse
}
var file_vertify_email_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vertify_email_proto_init() }
func file_vertify_email_proto_init() {
	if File_vertify_email_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vertify_email_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendVertifyEmailRequset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vertify_email_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VertifyEmailRequset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vertify_email_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VertifyEmailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vertify_email_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vertify_email_proto_goTypes,
		DependencyIndexes: file_vertify_email_proto_depIdxs,
		MessageInfos:      file_vertify_email_proto_msgTypes,
	}.Build()
	File_vertify_email_proto = out.File
	file_vertify_email_proto_rawDesc = nil
	file_vertify_email_proto_goTypes = nil
	file_vertify_email_proto_depIdxs = nil
}
