# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x02pb\"#\n\x0f\x46reeChatRequest\x12\x10\n\x08question\x18\x01 \x01(\t\"3\n\x0b\x43hatRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\")\n\x0c\x43hatResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03\x61ns\x18\x02 \x01(\t\"\x14\n\x12InitSessionRequest\"7\n\x13InitSessionResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x12\n\nsession_id\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FREECHATREQUEST']._serialized_start=18
  _globals['_FREECHATREQUEST']._serialized_end=53
  _globals['_CHATREQUEST']._serialized_start=55
  _globals['_CHATREQUEST']._serialized_end=106
  _globals['_CHATRESPONSE']._serialized_start=108
  _globals['_CHATRESPONSE']._serialized_end=149
  _globals['_INITSESSIONREQUEST']._serialized_start=151
  _globals['_INITSESSIONREQUEST']._serialized_end=171
  _globals['_INITSESSIONRESPONSE']._serialized_start=173
  _globals['_INITSESSIONRESPONSE']._serialized_end=228
# @@protoc_insertion_point(module_scope)
