# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_pawai.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import shared.pb.chat_pb2 as chat__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13service_pawai.proto\x12\x02pb\x1a\nchat.proto2\xb2\x01\n\x0cPawAIService\x12\x33\n\x08\x46reeChat\x12\x13.pb.FreeChatRequest\x1a\x10.pb.ChatResponse\"\x00\x12+\n\x04\x43hat\x12\x0f.pb.ChatRequest\x1a\x10.pb.ChatResponse\"\x00\x12@\n\x0bInitSession\x12\x16.pb.InitSessionRequest\x1a\x17.pb.InitSessionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pawai_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PAWAISERVICE']._serialized_start=40
  _globals['_PAWAISERVICE']._serialized_end=218
# @@protoc_insertion_point(module_scope)
