// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/RoyceAzure/sexy_gpt/account_service/worker (interfaces: ITaskDistributor)

// Package mock_worker is a generated GoMock package.
package mock_worker

import (
	context "context"
	reflect "reflect"

	worker "github.com/RoyceAzure/sexy_gpt/account_service/worker"
	gomock "github.com/golang/mock/gomock"
	asynq "github.com/hibiken/asynq"
)

// MockITaskDistributor is a mock of ITaskDistributor interface.
type MockITaskDistributor struct {
	ctrl     *gomock.Controller
	recorder *MockITaskDistributorMockRecorder
}

// MockITaskDistributorMockRecorder is the mock recorder for MockITaskDistributor.
type MockITaskDistributorMockRecorder struct {
	mock *MockITaskDistributor
}

// NewMockITaskDistributor creates a new mock instance.
func NewMockITaskDistributor(ctrl *gomock.Controller) *MockITaskDistributor {
	mock := &MockITaskDistributor{ctrl: ctrl}
	mock.recorder = &MockITaskDistributorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockITaskDistributor) EXPECT() *MockITaskDistributorMockRecorder {
	return m.recorder
}

// DistributeTaskSendVerifyEmail mocks base method.
func (m *MockITaskDistributor) DistributeTaskSendVerifyEmail(arg0 context.Context, arg1 *worker.PayloadSendVerifyEmail, arg2 ...asynq.Option) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DistributeTaskSendVerifyEmail", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeTaskSendVerifyEmail indicates an expected call of DistributeTaskSendVerifyEmail.
func (mr *MockITaskDistributorMockRecorder) DistributeTaskSendVerifyEmail(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeTaskSendVerifyEmail", reflect.TypeOf((*MockITaskDistributor)(nil).DistributeTaskSendVerifyEmail), varargs...)
}
