version: '3.9'
services:


  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=royce
      - POSTGRES_PASSWORD=royce
      - POSTGRES_DB=paw
    ports:
      - "5432:5432"
    volumes:
      - pawai_ps_volume:/var/lib/postgresql/data
    # command: ["sh", "/docker-entrypoint-initdb.d/init-db.sh"]



  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  pawai-service:
    build:
      context: .
      dockerfile: pawai.DockerFile
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    depends_on:
      - redis
    # command: ["/app/main"]
    command: ["python", "app.py"]

volumes:
  pawai_ps_volume: