// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/RoyceAzure/sexy_gpt/account_service/service (interfaces: IService)

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	db "github.com/RoyceAzure/sexy_gpt/account_service/repository/db/sqlc"
	gomock "github.com/golang/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// IsValidateUser mocks base method.
func (m *MockIService) IsValidateUser(arg0 context.Context, arg1 string) (*db.UserRoleView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValidateUser", arg0, arg1)
	ret0, _ := ret[0].(*db.UserRoleView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsValidateUser indicates an expected call of IsValidateUser.
func (mr *MockIServiceMockRecorder) IsValidateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValidateUser", reflect.TypeOf((*MockIService)(nil).IsValidateUser), arg0, arg1)
}
