DROP TABLE "user" CASCADE;
DROP TABLE "role" CASCADE;
DROP TABLE "user_role" CASCADE;
DROP TABLE "vertify_email" CASCADE;
DROP TABLE "session" CASCADE;
DROP TABLE "gpt_key" CASCADE;
DROP TABLE "account_key" CASCADE;
DROP TABLE "msg_session" CASCADE;
DROP TABLE "msg";
DROP TYPE "gpt_key_type";
DROP EXTENSION "uuid-ossp";